name: firebase_auth_app
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.6.0
  firebase_core: ^2.32.0

  user_repository:
    path: ./packages/user_repository
  bloc: ^8.1.4
  flutter_bloc: ^8.1.6
  equatable: ^2.0.7
  

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_lints: ^4.0.0

flutter:
 uses-material-design: true

 